networks:
  yandex-sprint-10-network:
    driver: bridge
    name: yandex-sprint-10-network

volumes:
  yandex_sprint_10_store_keycloak:
    name: yandex_sprint_10_store_keycloak
  yandex_sprint_10_exchange_postgres:
    name: yandex_sprint_10_exchange_postgres
  yandex_sprint_10_cash_postgres:
    name: yandex_sprint_10_cash_postgres
  yandex_sprint_10_transfer_postgres:
    name: yandex_sprint_10_transfer_postgres
  yandex_sprint_10_account_postgres:
    name: yandex_sprint_10_account_postgres


services:

  yandex-sprint-10-consul:
    container_name: yandex-sprint-10-consul
    image: hashicorp/consul:1.21.4
    command: [ "agent","-dev","-ui","-client","0.0.0.0", "-log-level","ERROR" ]
    ports: [ "8500:8500" ]
    networks:
      - yandex-sprint-10-network

  yandex-sprint-10-keycloak:
    container_name: yandex-sprint-10-keycloak
    image: quay.io/keycloak/keycloak:26.3.1
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_PORT: ${YANDEX_SPRINT_10_KEYCLOAK_PORT}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_URL: ${YANDEX_SPRINT_10_KEYCLOAK_HOSTNAME}:${YANDEX_SPRINT_10_KEYCLOAK_PORT}
      KC_HOSTNAME_ADMIN_URL: ${YANDEX_SPRINT_10_KEYCLOAK_HOSTNAME}:${YANDEX_SPRINT_10_KEYCLOAK_PORT}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${YANDEX_SPRINT_10_KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${YANDEX_SPRINT_10_KEYCLOAK_PASSWORD}
    ports:
      - ${YANDEX_SPRINT_10_KEYCLOAK_PORT}:${YANDEX_SPRINT_10_KEYCLOAK_PORT}
    command: start-dev --import-realm --hostname-strict=false
    networks:
      - yandex-sprint-10-network
    volumes:
      - yandex_sprint_10_store_keycloak:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import
    healthcheck:
      test: [ "CMD-SHELL", "echo > /dev/tcp/localhost/9000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  yandex-sprint-10-exchange-postgres:
    container_name: yandex-sprint-10-exchange-postgres
    image: postgres:${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_VERSION}
    volumes:
      - yandex_sprint_10_exchange_postgres:/var/lib/postgresql/data
    environment:
      PGPORT: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_PORT}
      POSTGRES_USER: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_NAME}
      POSTGRES_PASSWORD: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_PASSWORD}
      POSTGRES_DB: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_NAME}
    networks:
      - yandex-sprint-10-network

  yandex-sprint-10-cash-postgres:
    container_name: yandex-sprint-10-cash-postgres
    image: postgres:${YANDEX_SPRINT_10_CASH_POSTGRES_DB_VERSION}
    volumes:
      - yandex_sprint_10_cash_postgres:/var/lib/postgresql/data
    environment:
      PGPORT: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_PORT}
      POSTGRES_USER: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_NAME}
      POSTGRES_PASSWORD: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_PASSWORD}
      POSTGRES_DB: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_NAME}
    networks:
      - yandex-sprint-10-network

  yandex-sprint-10-transfer-postgres:
    container_name: yandex-sprint-10-transfer-postgres
    image: postgres:${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_VERSION}
    volumes:
      - yandex_sprint_10_transfer_postgres:/var/lib/postgresql/data
    environment:
      PGPORT: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_PORT}
      POSTGRES_USER: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_NAME}
      POSTGRES_PASSWORD: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_PASSWORD}
      POSTGRES_DB: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_NAME}
    networks:
      - yandex-sprint-10-network

  yandex-sprint-10-account-postgres:
    container_name: yandex-sprint-10-account-postgres
    image: postgres:${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_VERSION}
    volumes:
      - yandex_sprint_10_account_postgres:/var/lib/postgresql/data
    environment:
      PGPORT: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_PORT}
      POSTGRES_USER: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_NAME}
      POSTGRES_PASSWORD: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_PASSWORD}
      POSTGRES_DB: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_NAME}
    networks:
      - yandex-sprint-10-network
    ports: ["5433:5432"]


  yandex-sprint-10-account:
    container_name: yandex-sprint-10-account
    image: yandex-sprint-10-account:1.0.0
    build:
      context: ./account
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_PORT: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_PORT}
      YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_NAME: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_NAME}
      YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_NAME: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_NAME}
      YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_PASSWORD: ${YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_PASSWORD}
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
      YANDEX_SPRINT_10_KEYCLOAK_USER_MANAGEMENT_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_USER_MANAGEMENT_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_USER_MANAGEMENT_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_USER_MANAGEMENT_CLIENT_SECRET}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started
      yandex-sprint-10-account-postgres:
        condition: service_started

  yandex-sprint-10-blocker:
    container_name: yandex-sprint-10-blocker
    image: yandex-sprint-10-blocker:1.0.0
    build:
      context: ./blocker
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started

  yandex-sprint-10-cash:
    container_name: yandex-sprint-10-cash
    image: yandex-sprint-10-cash:1.0.0
    build:
      context: ./cash
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_CASH_POSTGRES_DB_PORT: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_PORT}
      YANDEX_SPRINT_10_CASH_POSTGRES_DB_NAME: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_NAME}
      YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_NAME: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_NAME}
      YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_PASSWORD: ${YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_PASSWORD}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started
      yandex-sprint-10-cash-postgres:
        condition: service_started

  yandex-sprint-10-exchange:
    container_name: yandex-sprint-10-exchange
    image: yandex-sprint-10-exchange:1.0.0
    build:
      context: ./exchange
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_PORT: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_PORT}
      YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_NAME: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_NAME}
      YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_NAME: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_NAME}
      YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_PASSWORD: ${YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_PASSWORD}
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:8080/actuator/health/readiness | grep -q '\"status\":\"UP\"'"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 30s
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started
      yandex-sprint-10-exchange-postgres:
        condition: service_started

  yandex-sprint-10-exchange-generator:
    container_name: yandex-sprint-10-exchange-generator
    image: yandex-sprint-10-exchange-generator:1.0.0
    build:
      context: ./exchange-generator
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started
      yandex-sprint-10-exchange:
        condition: service_healthy

  yandex-sprint-10-front-ui:
    container_name: yandex-sprint-10-front-ui
    image: yandex-sprint-10-front-ui:1.0.0
    build:
      context: ./front-ui
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started

  yandex-sprint-10-notification:
    container_name: yandex-sprint-10-notification
    image: yandex-sprint-10-notification:1.0.0
    build:
      context: ./notification
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started

  yandex-sprint-10-transfer:
    container_name: yandex-sprint-10-transfer
    image: yandex-sprint-10-transfer:1.0.0
    build:
      context: ./transfer
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_PORT: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_PORT}
      YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_NAME: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_NAME}
      YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_NAME: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_NAME}
      YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_PASSWORD: ${YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_PASSWORD}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started
      yandex-sprint-10-transfer-postgres:
        condition: service_started

  yandex-sprint-10-gateway:
    container_name: yandex-sprint-10-gateway
    image: yandex-sprint-10-gateway:1.0.0
    build:
      context: ./gateway
    ports: ["9090:9090"]
    networks:
      - yandex-sprint-10-network
    environment:
      YANDEX_SPRINT_10_KEYCLOAK_REALM: ${YANDEX_SPRINT_10_KEYCLOAK_REALM}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
      YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
      YANDEX_SPRINT_10_KEYCLOAK_USER_CLIENT_ID: ${YANDEX_SPRINT_10_KEYCLOAK_USER_CLIENT_ID}
    depends_on:
      yandex-sprint-10-keycloak:
        condition: service_healthy
      yandex-sprint-10-consul:
        condition: service_started
      yandex-sprint-10-front-ui:
        condition: service_started
      yandex-sprint-10-exchange:
        condition: service_healthy
