apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.k8sName }}
  labels:
    app: {{ .Values.k8sName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.k8sName }}
  template:
    metadata:
      labels:
        app: {{ .Values.k8sName }}
    spec:
      containers:
        - name: consul
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["agent","-dev","-ui","-client","0.0.0.0","-log-level","ERROR"]
          ports:
            - containerPort: {{ .Values.service.port }}
