spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      client:
        registration:
          bank-services-cc:
            provider: keycloak
            client-id: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
            client-secret: ${YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://yandex-sprint-10-keycloak:8080/realms/${YANDEX_SPRINT_10_KEYCLOAK_REALM}/protocol/openid-connect/token

clients:
  exchange-service:
    url: "http://yandex-sprint-10-exchange:8080"

application:
  scheduling:
    enable: true
