apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8sName }}
spec:
  selector:
    app: {{ .Values.k8sName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
