apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-common
data:
  YANDEX_SPRINT_10_KEYCLOAK_REALM: {{ .Values.global.keycloak.realm | quote }}
  YANDEX_SPRINT_10_KEYCLOAK_HOSTNAME: {{ .Values.global.keycloak.internalUrl | quote }}
  YANDEX_SPRINT_10_KEYCLOAK_PORT: {{ .Values.global.keycloak.port | quote }}
